import time


# Member Acct info
acctNum = 123456
memberPin = 1234
balance = float("5000")
attempts = 3

print()
print()
print("-----------------------------------------------------------------")
print("-----------------------------------------------------------------")
print("-----------------------------------------------------------------")
print("------------------- Welcome to SDEV 220 Bank! -------------------")
print("-----------------------------------------------------------------")
print("-----------------------------------------------------------------")
print("-----------------------------------------------------------------")


# Progam info
print()
print()
time.sleep(1)
print("    ---------------------")
time.sleep(1)
print("    -'SHORT CIRCUIT ATM'-")
time.sleep(1)
print("    --Software by TivBit-")
time.sleep(1)
print("    -----Spring 2023-----")
time.sleep(1)
print("    ---------------------")
time.sleep(1)
print()
print()
time.sleep(1.5)
while attempts != 0:
    time.sleep(1)
    acctVerify = int(input("Please enter your account number: "))
    print()
    print()
    if acctVerify != acctNum:
        attempts -= 1
        time.sleep(1)
        print("----------------------------------")
        print("Malfunction. Need input.")
        print("----------------------------------")
        print()
        print()
        time.sleep(1)
        print("------------------------------------------------------------------")
        print(f"You entered an invalid account number.  You have {attempts} attempts left.")
        print("------------------------------------------------------------------")

    else:    
        print()
        print()
        time.sleep(1)
        pinPass = float(input("Please enter your 4 digit pin: "))

        if pinPass != memberPin: 
            attempts -= 1
            print()
            print()
            time.sleep(1)
            print("---------------------------")
            print("Malfunction. Need input.")
            print("---------------------------")
            print()
            print()
            time.sleep(1)
            print("-------------------------------------------------------------------")
            print(f"You entered the incorrect pin.  You have {attempts} attempts left.")
            print("-------------------------------------------------------------------")
            break
        else:
            print()
            print()
            time.sleep(1)
            print("----------------------------------")
            print("You have successfully logged in!")
            print("----------------------------------")
            print()
            print()
            time.sleep(1)
            print("--------------------------")
            print("---NUMBER 5 IS ALIVE!!!---")
            print("--------------------------")
            print()
            print()
            print()
            print()
            time.sleep(1.5)
        memberChoice = input("What would you like to do today?  1= Balance, 2= Withdraw: ")
        if memberChoice == "1":
            print()
            print()
            time.sleep(1)
            print("-----------------------------------------------------------")
            print(f"Your balance is: ${balance}.")
            print("-----------------------------------------------------------")
        if memberChoice == "2":
            withdrawAmount = float(input("Enter the amount you would like to withdraw:  $"))
            if withdrawAmount <= balance:
                newBalance = balance - withdrawAmount
                time.sleep(1)
                print()
                print()
                print("--------------------------------------------------------------------")
                print(f"Your withdraw in the amount of {withdrawAmount} has been processed.")
                print("--------------------------------------------------------------------")
                print()
                print()
                time.sleep(1)
                print("-------------------------------------------------------")
                print("Please take your money, secure your card/digital card.")
                print("-------------------------------------------------------")
                print()
                print()
                print()
                time.sleep(1)
                print("-----------------------------------------")
                print(f"Your new balance is now: ${newBalance}.")
                print("-----------------------------------------")
                print()
                print()
                time.sleep(5)
                print("------------------------------------------------------------")
                print("Thank you for banking with SDEV 220 Bank.  Have a great day!")
                print("------------------------------------------------------------")
                print()
                print()
            else:
                print()
                print()
                time.sleep(1.5)
                print("-----------------------------------------------")
                print("--------------Unable. Malfunction.-------------")
                print("Insufficient funds.  Your balance is {balance}.")
                print("-----------------------------------------------")
                print()
                print()
                time.sleep(1.5)
            
            print("-----------------------------------------------------------------")
            print("-----------------------------------------------------------------")
            print("-------------------END OF PROGRAM.  GOOD BYE---------------------")
            print("-----------------------------------------------------------------")
            print("-----------------------------------------------------------------")
            print()
            print()
            time.sleep(1)
            print("-----------------------------------------------------------------")
            time.sleep(1)
            print("----------------------------Credits:-----------------------------")
            time.sleep(1)
            print("-----------------------------------------------------------------")
            time.sleep(1)
            print("------------------------Python Coded by:-------------------------")
            time.sleep(1)
            print("--------------------- Nativida Iris Barlow ----------------------")
            time.sleep(1)
            print("-----------------------------------------------------------------")
            time.sleep(1)
            print("-----------------------------------------------------------------")
            time.sleep(1)
            print("--------------------Instructor: Chris Francis--------------------")
            time.sleep(1)
            print("--------------------Ivy Tech Community College-------------------")
            time.sleep(1)
            print("-----------------------------------------------------------------")
            time.sleep(1)
            print("-----------------------------------------------------------------")
            break

